### ISSUE TITLE
Review Main readme

### ISSUE THREAD

**Issue by savvyyai** [savvyyai/playground#2]

**Comment by tyler-speakman** [comment]
@savvyyai suggestions:
- _"A simple lending portal that allows developers to experiment with different implementations. The admin portal is designed to be white-labelled for multiple customers, so code-reuse is of the utmost importance."_ *->* _"A portal that allows developers to experiment with different implementations. It is designed to be white-labelled for multiple customers, so code-reuse is of the utmost importance."_ * (by mentioning lending portal and admin portal it sounds like there's multiple portals)
- _"Generate modules using cli commands"_ *->* _"Generate modules using Ng commands"_ (it'll read similar to _"Generate state code using Nx commands"_)
- Replace all references to "my-app" with "playground-web" (i.e., `ng serve my-app` *->* `ng serve playground-web`)
-`ng e2e my-app` *->* `ng e2e playground-web-e2e`

**Comment by cesar-savvyy** [comment]
I was hoping to keep the auto generated documentation as is.
